config/routes.rb
Rails.application.routes.draw do
  root to: "tweet#index"
  get 'tweet/index'
  get 'tweet/new'
  post 'tweet/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def index
  end

  def new

  end

  def create
    Tweet.create(params.permit(:image, :text))
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracPictweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/tweet/index.html.erb
<div class="contents row">
  <p>hello</p>
  <div>
    <%= link_to "投稿", tweet_new_path, :class => 'get'%>
  </div>
</div>

app/views/tweet/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweet/create', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <input placeholder="Image Url" type="text" name="image">
      <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>
</div>